### 1. Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np


arr = np.zeros(10,dtype = int)
arr[4] = 1

print(arr)

[0 0 0 0 1 0 0 0 0 0]


### 2. Create a vector with values ranging from 10 to 49.

In [4]:
array_1 = np.arange(10,50)

array_1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 3. Create a 3x3 matrix with values ranging from 0 to 8

In [5]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [6]:
n_array = np.array([1,2,0,0,4,0])

print("Original array:")
print(n_array)

# np.nonzero()
print("\nIndices of null elements:")

res = np.nonzero(n_array == 0)
print(res)

Original array:
[1 2 0 0 4 0]

Indices of null elements:
(array([2, 3, 5], dtype=int64),)


### 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [7]:
import numpy as np
n_array = np.random.random((10,10))

print("the original array",n_array)

print("\n\n")
print("the minimum value of n_array: \n",n_array.min())
      
print("\n\n")
print("the maximun value of n_array: \n",n_array.max())

the original array [[0.97034266 0.85797901 0.57378139 0.86938651 0.59363173 0.20020882
  0.93186368 0.30865975 0.08339909 0.81007263]
 [0.66179253 0.23452259 0.1307347  0.69251155 0.02672898 0.49976137
  0.59793784 0.33298091 0.88630142 0.05930445]
 [0.99594522 0.32775766 0.25229597 0.79491084 0.6601397  0.63325698
  0.62909612 0.59137919 0.14077442 0.4674482 ]
 [0.93991996 0.58835296 0.11727575 0.21058095 0.74520359 0.49715823
  0.84007844 0.2370188  0.72803251 0.29700326]
 [0.45444424 0.56166934 0.55053067 0.47853971 0.99487535 0.41277162
  0.90340468 0.68673144 0.01380345 0.36927994]
 [0.51907777 0.62246942 0.63379427 0.35731004 0.56910043 0.34724444
  0.55274601 0.58911821 0.77361584 0.23542548]
 [0.72257111 0.36972976 0.35725502 0.44469996 0.43934296 0.34796538
  0.89270228 0.84139241 0.6838643  0.00976084]
 [0.1274859  0.58126642 0.79671393 0.06851493 0.40070464 0.18254125
  0.51509559 0.43059767 0.0136649  0.52986404]
 [0.64981187 0.39956554 0.06091802 0.21767994 0.97071997 0.54

### 6. Create a random vector of size 30 and find the mean value.

In [8]:
import numpy as np

z = np.random.random(30)
print("the random array is: \n",z)

mean_1 = z.mean()
print("\n\nthe mean value of array: \n ",mean_1)

the random array is: 
 [0.4700834  0.20039913 0.75397573 0.34102356 0.53313282 0.64350702
 0.09840404 0.13914394 0.90827336 0.27402374 0.54833795 0.7708
 0.02076128 0.95984926 0.87664569 0.41055601 0.71333667 0.57301728
 0.82496615 0.98650898 0.57812275 0.18032653 0.58249638 0.03628029
 0.09153972 0.63584802 0.5135651  0.13917664 0.67869165 0.32261798]


the mean value of array: 
  0.49351370233506475
